name: anaconda upload packages
description: Upload conda packages to a conda channel

branding:
  icon: share
  color: green

inputs:
  packages:
    description: Path of packages to upload
    required: true
    default: ${{ github.workspace }}/conda-build/**/*.tar.bz2
  user:
    description: Channel on anaconda.org
    required: true
  token:
    description: Binstar access token to upload to anaconda.org
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export PYTHONUNBUFFERED=1
        $CONDA/bin/conda install --yes --quiet anaconda-client
        if [ -z $ANACONDA_API_TOKEN ]; then
          echo "Not uploading conda package since no token was provided."
        else
          $CONDA/bin/anaconda upload --skip-existing --label main ${{ inputs.packages }}
        fi
      env:
        ANACONDA_API_TOKEN: ${{ inputs.token }}
