name: asv benchmarks
description: Run AirSpeedVelocity benchmarks and prepare results as github-pages

branding:
  icon: activity
  color: white

inputs:
  packages:
    description: Whether to use "mamba" or "pixi" to install packages.
    required: false
    default: mamba

runs:
  using: composite
  steps:
    - name: Install ASV (mamba)
      shell: bash -l {0}
      run: |
        mamba install --quiet --yes asv
        # Work around https://github.com/airspeed-velocity/asv/issues/1396 until it is fixed in the published asv.
        mamba install -n base --quiet --yes 'conda<24.3'
      if: ${{ inputs.packages == 'mamba' }}
    - name: Setup ASV Configuration
      shell: bash -l {0}
      run: |
        export PYTHONUNBUFFERED=1

        cat <<EOF > ~/.asv-machine.json
        {
            "azure": {
                "arch": "x86_64",
                "cpu": "Standard_DS2_v2",
                "machine": "Azure",
                "os": "Linux",
                "ram": "61830880"
            },
            "version": 1
        }
        EOF
    - name: Setup Repository
      shell: bash -l {0}
      run: |
        # ASV will run benchmarks on the HEAD of master. So we need to pretend that this is where we are at the moment.
        git checkout -b master || true
    - name: Run Benchmarks (mamba)
      shell: bash -l {0}
      run: |
        asv run -v --machine=azure
      if: ${{ inputs.packages == 'mamba' }}
    - name: Run Benchmarks (pixi)
      shell: bash -l {0}
      run: |
        asv run -v --machine=azure --python=same
      if: ${{ inputs.packages == 'pixi' }}
    - name: Rerender GitHub Pages
      shell: bash -l {0}
      run: |
        asv publish --no-pull --verbose --html-dir .asv/html
